apiVersion: v1
kind: Service
metadata:
  name: proguven-frontend-service
spec:
  type: NodePort
  selector:
    app: proguven-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32000
